### ISSUE TITLE
Navbar color

### ISSUE THREAD

**Issue by johnnykkf** [ken20082006/teamform-seed#49]
Light blue color seeems not look good, isn't it?

**Comment by ken20082006** [comment]
try other color and see

**Comment by Kevinoust** [comment]
I suggest #404040

**Comment by FAIFAIBENNANA** [comment]
i changed to more solid blue, see if looks ok now.
if not, we can change to light grey (more formal)

**Comment by ken20082006** [comment]
the div for navBar is too small now.

stroll bar have been show up
